apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Name }}
  creationTimestamp: null
  name: configmap-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
data:
# it's for furture non-sensitive data information usage, meanwhile please ignore it
