# for HPA scaling
{{- if .Values.horizontalScaler.require -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: {{ .Values.horizontalScaler.maxReplicas }}
  minReplicas: {{ .Values.horizontalScaler.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.horizontalScaler.memoryTarget }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.horizontalScaler.cpuTarget }}
{{- end -}}