podResources:
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.25
      memory: 0.5Gi

extraPodConfig:
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 50

postgres:
  storage: 10Gi # GiB
  storageClassName: local
  volume: database-data
  name: postgres

container:
  image: techchallengeapp
  pullPolicy: Always
  port: 3000
  replica: 1

horizontalScaler:
  required: false

ingress:
  certificationArn: { ARN }
  healthcheckPath: healthcheck
